### ISSUE TITLE
Extension stops working with Uncrustify 0.74 (solved)

### ISSUE THREAD

**Issue by PawelWozniak** [zachflower/vscode-uncrustify#8]
I just upgraded Uncrustify.exe from 0.73f to 0.74 and extension stopped working. 
When I run "format document" - nothing happen.
Replacing .exe back to 073f restore functionality.

I don't see any errors in VSCode window or logs.

Windows 10 x64, Uncrustify x64, VSCode 1.62.3

**Comment by PawelWozniak** [comment]
False alarm. I have turned on debug logs in extension config and got this:
Debug: uncrustify exited with error: d:\git\development\config\uncrustify.cfg: line 2: Character at position 19, is not printable.
There was a comment in cfg file with a Polish character in my name Paweł<-- and that was an issue. 
Apparently the previous version has not checked that.

**Comment by zachflower** [comment]
Glad you were able to get it figured out!
